# Generated by Django 3.0 on 2020-02-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion_model',
            name='author',
            field=models.CharField(default='sean', max_length=240),
        ),
    ]
