# Generated by Django 3.0 on 2020-02-23 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_suggestion_model_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion_model',
            name='author',
        ),
    ]
